apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sftp

resources:
- 01-namespace.yaml
- 02-pvc.yaml
- 21-deployment.yaml
- 22-service.yaml

generatorOptions:
  disableNameSuffixHash: true  

secretGenerator:
  - name: sftp-credentials
    envs:
      - .env.sftp.secret

configMapGenerator:
  - name: sftp-config
    literals:
      - SFTP_FOLDER=nuxeo


# labels:
# - includeSelectors: true
#   pairs:
#     app.kubernetes.io/managed-by: kustomize
#     app.kubernetes.io/part-of: sftp-stack
