apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        uid: prometheus
        url: http://prometheus-service:9090
        isDefault: true
        editable: true
      - name: Loki
        type: loki
        access: proxy
        uid: loki
        url: http://loki-service.loki.svc.cluster.local:3100
        isDefault: false
        editable: true
        jsonData:
          maxLines: 1000
