apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce # This means the volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 10Gi # Request 10 Gigabytes of storage
