apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8080 # Service port
      targetPort: 8080 # Container port
    - name: agent
      protocol: TCP
      port: 50000
      targetPort: 50000
  type: ClusterIP # Expose inside the cluster
