apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  # MetalLB official manifest (replace with latest if needed)
  - https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml
  #- 03-duplicate-port-fix.yaml

# labels:
#   - includeSelectors: true
#     pairs:
#       app.kubernetes.io/managed-by: kustomize
#       app.kubernetes.io/part-of: metallb-stack