apiVersion: v1
kind: ConfigMap
metadata:
  name: nuxeo-common-config
data:
  NUXEO_ENVIRONMENT: "dev"
  NUXEO_MONGODB_DBNAME: "nuxeo-base-2023"
  NUXEO_PROFILES: "s3binaries,mongodb"
  NUXEO_BLOB_MANAGER: "org.nuxeo.ecm.blob.s3.S3BlobProvider"

  NUXEO_ELASTICSEARCH_ENABLED: "true"
  NUXEO_ELASTICSEARCH_ADDRESSLIST: "elasticsearch-es-http.elasticsearch.svc.cluster.local:9200"
  NUXEO_ELASTICSEARCH_HTTPONLY_BASEURL: "http://elasticsearch-es-http.elasticsearch.svc.cluster.local:9200"
  NUXEO_ELASTICSEARCH_INDEXNAME: "nuxeo-base"

  # Kafka configuration for all pods
  NUXEO_KAFKA_ENABLED: "true"
  NUXEO_KAFKA_TOPICPREFIX: "nuxeo-base-"
  NUXEO_KAFKA_BOOTSTRAP_SERVERS: "kafka-kafka-bootstrap.kafka.svc:9092"
  NUXEO_STREAM_WORK_ENABLED: "true"
  JAVA_OPTS: "-XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=50"

  # S3 Blob Storage (MinIO)
  NUXEO_AWS_REGION: "us-east-1"
  NUXEO_S3STORAGE_BUCKET: "nuxeo-blob-storage"
  NUXEO_S3STORAGE_BUCKET_PREFIX: "nuxeo-base/"
  
  NUXEO_S3STORAGE_ENDPOINT: "http://minio-service.minio.svc.cluster.local:9000"
  NUXEO_S3STORAGE_PATHSTYLEACCESS: "true"


  # Runtime patch for headless operation
  NUXEO_RUNTIME_MP_DIR: "empty"

  # Logs
  ROOT_LOG_LEVEL: ERROR
  DEV_LOG_LEVEL: ERROR

  # Single-broker Kafka (dev)
  NUXEO_STREAM_KAFKA_DEFAULT_REPLICATION_FACTOR: "1"

  # Cluster settings
  NUXEO_CLUSTER_ENABLED: "true"








