apiVersion: v1
kind: ConfigMap
metadata:
  name: nuxeo-api-config
data:
  NUXEO_RUN_MODE: "api"
  NUXEO_DEV: "true"
  NUXEO_SERVER_HTTP_ENABLED: "true"
  NUXEO_SERVER_HTTPS_ENABLED: "true"
  NUXEO_BIND_ADDRESS: "0.0.0.0"

  # Enable bulk action submission
  NUXEO_BULK_ACTION_ENABLED: "true"

  # Optional debug
  NUXEO_SELECTION_SELECT_ALL_ENABLED: "true"

  # Work processing
  #NUXEO_WORKER_ENABLED: "false"
  NUXEO_WORK_PROCESSING_ENABLED: "false"
  NUXEO_STREAM_PROCESSING_ENABLED: "false"
