apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab

resources:
- ../../../base/gitlab
- ingress.yaml

images:
- name: gitlab/gitlab-ce
  newName: gitlab/gitlab-ce
  newTag: 18.8.2-ce.0

configMapGenerator:
  - name: gitlab-config
    envs:
      - .env.gitlab

patches:
- path: patch-external-url.yaml

replacements:
  - source:
      kind: ConfigMap
      name: gitlab-config
      fieldPath: data.GITLAB_HOST
    targets:
      - select:
          kind: Ingress
          name: gitlab-ingress
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
  - source:
      kind: ConfigMap
      name: gitlab-config
      fieldPath: data.CLUSTER_ISSUER
    targets:
      - select:
          kind: Ingress
          name: gitlab-ingress
        fieldPaths:
          - metadata.annotations.cert-manager\.io/cluster-issuer