apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce # This means the volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 5Gi # Request 5 Gigabytes of storage
