apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 # Service port
      targetPort: 5432 # Container port
  type: ClusterIP # Expose internally within the cluster
