apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_ADMIN
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_ADMIN_PASSWORD
        - name: KC_HOSTNAME_STRICT
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HOSTNAME_STRICT
        - name: KC_HTTP_ENABLED
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HTTP_ENABLED
        - name: KC_PROXY
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_PROXY
        - name: KC_HOSTNAME_ADMIN_URL
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HOSTNAME_ADMIN_URL
        - name: KC_HOSTNAME_URL
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HOSTNAME_URL
        - name: KC_HTTP_RELATIVE_PATH
          value: "/"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"