apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab

resources:
  - 01-namespace.yaml
  - 02-pvc.yaml
  - 03-deployment.yaml
  - 04-service.yaml

secretGenerator:
  - name: gitlab-root-password
    envs:
      - .env.gitlab.secret
      
generatorOptions:
  disableNameSuffixHash: true  