apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager/
  - storage/
  - keycloak/
  - elastic-operator/
  - elasticsearch/
  - kafka-operator/
  - kafka/
  - mongo/
  - minio/
  - mailhog/
  - loki/
  - monitoring/
  - sftp/
  - redis/
  - postgres/
  - gitlab/
  - metallb/
  # - jenkins/