apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio

resources:
  - 01-namespace.yaml
  - 02-pvc.yaml
  - 03-bucket-init-job.yaml
  - 04-deployment.yaml
  - 05-service-clusterip.yaml

secretGenerator:
  - name: minio-secret
    envs:
      - .env.minio.secret
generatorOptions:
  disableNameSuffixHash: true  

# labels:
# - includeSelectors: true
#   pairs:
#     app.kubernetes.io/managed-by: kustomize
#     app.kubernetes.io/part-of: minio-stack

