apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-loki-pvc.yaml
  - 03-loki-configmap.yaml
  - 04-loki-deployment.yaml
  - 05-loki-service.yaml
  - 06-promtail-configmap.yaml
  - 07-promtail-daemonset.yaml
  - 08-promtail-service.yaml
