apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxeo-worker-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: nuxeo-worker
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
